In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([2,0,-3, 10 , 90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3 10 90], shape=(5,), dtype=int32)


In [17]:
tensor_two_d= tf.constant([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,25,9]],
    [[1,2,3],[4,5,6],[7,8,145]]
])
# print(tensor_two_d)
print(tensor_two_d)

tf.Tensor(
[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[  1   2   3]
  [  4   5   6]
  [  7  25   9]]

 [[  1   2   3]
  [  4   5   6]
  [  7   8 145]]], shape=(3, 3, 3), dtype=int32)


In [16]:
tensor_four_d = tf.constant([
[
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,25,9]],
    [[1,2,3],[4,5,6],[7,8,145]],
],
[
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,25,9]],
    [[1,2,3],[4,5,6],[7,8,145]],
],
[
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,25,9]],
    [[1,2,3],[4,5,6],[7,8,145]],
],
])
print(tensor_four_d)

tf.Tensor(
[[[[  1   2   3]
   [  4   5   6]
   [  7   8   9]]

  [[  1   2   3]
   [  4   5   6]
   [  7  25   9]]

  [[  1   2   3]
   [  4   5   6]
   [  7   8 145]]]


 [[[  1   2   3]
   [  4   5   6]
   [  7   8   9]]

  [[  1   2   3]
   [  4   5   6]
   [  7  25   9]]

  [[  1   2   3]
   [  4   5   6]
   [  7   8 145]]]


 [[[  1   2   3]
   [  4   5   6]
   [  7   8   9]]

  [[  1   2   3]
   [  4   5   6]
   [  7  25   9]]

  [[  1   2   3]
   [  4   5   6]
   [  7   8 145]]]], shape=(3, 3, 3, 3), dtype=int32)
