In [129]:
import tensorflow as tf

In [130]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [131]:
tensor_one_d = tf.constant([2,0,-3, 10 , 90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3 10 90], shape=(5,), dtype=int32)


In [132]:
tensor_two_d= tf.constant([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,25,9]],
    [[1,2,3],[4,5,6],[7,8,145]]
])
print(tensor_two_d)
print(tensor_two_d[0, 1:,0:2])
print(tensor_two_d[0, 0,:])

tf.Tensor(
[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[  1   2   3]
  [  4   5   6]
  [  7  25   9]]

 [[  1   2   3]
  [  4   5   6]
  [  7   8 145]]], shape=(3, 3, 3), dtype=int32)
tf.Tensor(
[[4 5]
 [7 8]], shape=(2, 2), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [133]:
tensor_four_d = tf.constant([
[
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,25,9]],
    [[1,2,3],[4,5,6],[7,8,145]],
],
[
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,25,9]],
    [[1,2,3],[4,5,6],[7,8,145]],
],
[
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,25,9]],
    [[1,2,3],[4,5,6],[7,8,145]],
],
],dtype=tf.float64)
print(tensor_four_d)
print(tensor_four_d.ndim)

tf.Tensor(
[[[[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.   8.   9.]]

  [[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.  25.   9.]]

  [[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.   8. 145.]]]


 [[[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.   8.   9.]]

  [[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.  25.   9.]]

  [[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.   8. 145.]]]


 [[[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.   8.   9.]]

  [[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.  25.   9.]]

  [[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.   8. 145.]]]], shape=(3, 3, 3, 3), dtype=float64)
4


In [134]:
tensor_string = tf.constant(["Hello world", "hi"])
print(tensor_string)

tf.Tensor([b'Hello world' b'hi'], shape=(2,), dtype=string)


In [135]:
import numpy as np 
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [136]:
my_eye = tf.eye(5)
print(3*my_eye)

tf.Tensor(
[[3. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 3.]], shape=(5, 5), dtype=float32)


In [137]:
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns = None,
    batch_shape = [2,4],
    dtype  = tf.dtypes.float32,
    name = None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [138]:
my_scalar = tf.fill(
    [2,3,10],10,
    name = None
    )
print(my_scalar)

tf.Tensor(
[[[10 10 10 10 10 10 10 10 10 10]
  [10 10 10 10 10 10 10 10 10 10]
  [10 10 10 10 10 10 10 10 10 10]]

 [[10 10 10 10 10 10 10 10 10 10]
  [10 10 10 10 10 10 10 10 10 10]
  [10 10 10 10 10 10 10 10 10 10]]], shape=(2, 3, 10), dtype=int32)


In [139]:
my_zeros_matrix =  tf.zeros(
    [5,5],
    name = None,
    dtype  = tf.dtypes.int32,   
)
print(my_zeros_matrix)

tf.Tensor(
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]], shape=(5, 5), dtype=int32)


In [140]:
t = tf.constant([[1,1,1],[2,2,2]])
print(t)
print(tf.rank(t))

tf.Tensor(
[[1 1 1]
 [2 2 2]], shape=(2, 3), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [141]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
rank_of_matrix = tf.rank(t)  # 3
print(rank_of_matrix)

tf.Tensor(3, shape=(), dtype=int32)


In [142]:
t = tf.constant([[1,1,1],[2,2,2]])
tf.size(t,out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [143]:
import random
random_tensor = tf.random.normal(
    [3,3],
    mean =50,
    stddev = 1.0,
    dtype=tf.dtypes.float64,
    seed = None,
    name = None  

)
print(random_tensor)

tf.Tensor(
[[49.25306461 50.76251697 50.39666384]
 [49.61930282 51.30323811 51.77153661]
 [49.85178166 50.57304295 49.05409085]], shape=(3, 3), dtype=float64)


In [144]:

random_tensor=tf.random.uniform(
    [2,2],
    minval=0,
    maxval=1000,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[133 946]
 [105 472]], shape=(2, 2), dtype=int32)


In [145]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))


tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)


In [146]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:6])
print(tensor_indexed[2:])


tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)
tf.Tensor([ 2  4  6 66  7], shape=(5,), dtype=int32)


In [147]:
tensor_two_d = tf.constant(
    [
        [1,2,0],
        [3,5,-1],
        [1,5,6],
        [2,3,8]
    ]
)
print(tensor_two_d)
print(tensor_two_d[0:3,:])
print(tensor_two_d[3,:])
print(tensor_two_d[:,-2])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)
tf.Tensor([2 3 8], shape=(3,), dtype=int32)
tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [148]:
x_abs = tf.constant([-2.25, 4])
print(tf.abs(x_abs))

tf.Tensor([2.25 4.  ], shape=(2,), dtype=float32)


In [149]:
x1= tf.constant([[5,2,5,6,4,4,85], [5,2,5,6,4,4,85]] , dtype=tf.float32)
x2 = tf.constant([7], dtype=tf.float32)
x2_streched = tf.constant([[7],[7],[7],[7],[7],[7],[7]], dtype=tf.float32)

print(x1)
print(x1.shape)
print(x2)
print(x2.shape)
print(x2_streched)
print(x2_streched.shape)
print(tf.math.multiply(x1, x2))

tf.Tensor(
[[ 5.  2.  5.  6.  4.  4. 85.]
 [ 5.  2.  5.  6.  4.  4. 85.]], shape=(2, 7), dtype=float32)
(2, 7)
tf.Tensor([7.], shape=(1,), dtype=float32)
(1,)
tf.Tensor(
[[7.]
 [7.]
 [7.]
 [7.]
 [7.]
 [7.]
 [7.]], shape=(7, 1), dtype=float32)
(7, 1)
tf.Tensor(
[[ 35.  14.  35.  42.  28.  28. 595.]
 [ 35.  14.  35.  42.  28.  28. 595.]], shape=(2, 7), dtype=float32)


In [150]:
x_argmax = tf.constant(
    [
        [2,20,30,3,6],
        [3,11,16,1,8],
        [14,45,23,5,27]
    ]
)
print(x_argmax)
print(x_argmax.shape)
print(tf.math.argmax(x_argmax))
print(tf.math.argmax(random_tensor))
print(random_tensor)

tf.Tensor(
[[ 2 20 30  3  6]
 [ 3 11 16  1  8]
 [14 45 23  5 27]], shape=(3, 5), dtype=int32)
(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([0 0], shape=(2,), dtype=int64)
tf.Tensor(
[[133 946]
 [105 472]], shape=(2, 2), dtype=int32)


In [151]:
# create two matrix 
import random
x1 = tf.random.normal(
    [3,3],
    mean =1,
    stddev = 1.0,
    dtype=tf.dtypes.float64,
    seed = None,
    name = None  
)
x2 = tf.random.normal(
    [3,3],
    mean =1,
    stddev = 1.0,
    dtype=tf.dtypes.float64,
    seed = None,
    name = None  
)
multiply_x1andx2 = tf.experimental.numpy.multiply(x1, x2)
print(x1)
print(x2)
print(multiply_x1andx2)


tf.Tensor(
[[ 2.2368121   3.73198576  0.84409061]
 [ 0.26348036  2.52896688  1.28593284]
 [ 1.73894242 -0.98620837  2.0264812 ]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[ 1.10129119  0.01695981  2.65787672]
 [ 1.32931166  1.28694533  0.29745246]
 [ 1.81972057 -1.00005567  1.34865489]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[2.46338145 0.06329376 2.24348877]
 [0.35024751 3.25464211 0.38250389]
 [3.16438929 0.98626327 2.73302379]], shape=(3, 3), dtype=float64)


Getting Started
Please also see TensorFlow NumPy Guide.

In the code snippets below, we will assume that tf.experimental.numpy is imported as tnp and NumPy is imported as np

In [156]:
print(tensor_two_d)
tf.math.top_k(tensor_two_d, k=2, sorted=True)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[2, 1],
       [5, 3],
       [6, 5],
       [8, 3]])>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 0],
       [1, 0],
       [2, 1],
       [2, 1]])>)

In [158]:
x1 = tf.constant([[1,2,3], [4,5,6]], dtype=tf.float32) # 2x3 * 3x2
#create here 3x2 matrix
x2 = tf.constant([[1,2],[3,4],[5,6]], dtype=tf.float32)
mat_multiply = tf.linalg.matmul(
    x1,
    x2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)
print(mat_multiply)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)
