In [3]:
import tensorflow as tf

In [36]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [37]:
tensor_one_d = tf.constant([2,0,-3, 10 , 90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3 10 90], shape=(5,), dtype=int32)


In [38]:
tensor_two_d= tf.constant([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,25,9]],
    [[1,2,3],[4,5,6],[7,8,145]]
])
# print(tensor_two_d)
print(tensor_two_d)

tf.Tensor(
[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[  1   2   3]
  [  4   5   6]
  [  7  25   9]]

 [[  1   2   3]
  [  4   5   6]
  [  7   8 145]]], shape=(3, 3, 3), dtype=int32)


In [39]:
tensor_four_d = tf.constant([
[
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,25,9]],
    [[1,2,3],[4,5,6],[7,8,145]],
],
[
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,25,9]],
    [[1,2,3],[4,5,6],[7,8,145]],
],
[
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,25,9]],
    [[1,2,3],[4,5,6],[7,8,145]],
],
],dtype=tf.float64)
print(tensor_four_d)

tf.Tensor(
[[[[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.   8.   9.]]

  [[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.  25.   9.]]

  [[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.   8. 145.]]]


 [[[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.   8.   9.]]

  [[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.  25.   9.]]

  [[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.   8. 145.]]]


 [[[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.   8.   9.]]

  [[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.  25.   9.]]

  [[  1.   2.   3.]
   [  4.   5.   6.]
   [  7.   8. 145.]]]], shape=(3, 3, 3, 3), dtype=float64)


In [40]:
tensor_string = tf.constant(["Hello world", "hi"])
print(tensor_string)

tf.Tensor([b'Hello world' b'hi'], shape=(2,), dtype=string)


In [41]:
import numpy as np 
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [43]:
my_eye = tf.eye(5)
print(3*my_eye)

tf.Tensor(
[[3. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 3.]], shape=(5, 5), dtype=float32)


In [53]:
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns = None,
    batch_shape = [2,4],
    dtype  = tf.dtypes.float32,
    name = None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [68]:
my_scalar = tf.fill(
    [2,3,10],10,
    name = None
    )
print(my_scalar)

tf.Tensor(
[[[10 10 10 10 10 10 10 10 10 10]
  [10 10 10 10 10 10 10 10 10 10]
  [10 10 10 10 10 10 10 10 10 10]]

 [[10 10 10 10 10 10 10 10 10 10]
  [10 10 10 10 10 10 10 10 10 10]
  [10 10 10 10 10 10 10 10 10 10]]], shape=(2, 3, 10), dtype=int32)


In [74]:
my_zeros_matrix =  tf.zeros(
    [2,5,10],
    name = None,
    dtype  = tf.dtypes.int16,   
)
print(my_ones)

tf.Tensor(
[[[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]], shape=(2, 5, 10), dtype=int16)


In [76]:
ones_line_tensor = tf.ones_like(my_ones)
print(ones_lie_tensor)


tf.Tensor(
[[[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]], shape=(2, 5, 10), dtype=int16)


In [79]:
t = tf.constant([[1,1,1],[2,2,2]])
print(t)
print(tf.rank(t))

tf.Tensor(
[[1 1 1]
 [2 2 2]], shape=(2, 3), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [81]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
rank_of_matrix = tf.rank(t)  # 3
print(rank_of_matrix)

tf.Tensor(3, shape=(), dtype=int32)


In [5]:
t = tf.constant([[1,1,1],[2,2,2]])
tf.size(t,out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [16]:
import random
random_tensor = tf.random.normal(
    [3,3],
    mean =50,
    stddev = 1.0,
    dtype=tf.dtypes.float64,
    seed = None,
    name = None  

)
print(random_tensor)

tf.Tensor(
[[50.09677466 51.39580547 49.13299734]
 [50.0043695  49.28372324 50.59451567]
 [48.80489337 49.22281957 49.70057739]], shape=(3, 3), dtype=float64)
